ALTER TABLE "Guesthouse"
  ADD COLUMN IF NOT EXISTS "videoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "videoPublicId" TEXT;

CREATE TABLE IF NOT EXISTS "RoomImage" (
  "id" SERIAL NOT NULL,
  "roomId" INTEGER NOT NULL,
  "url" TEXT NOT NULL,
  "publicId" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RoomImage_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "RoomImage_roomId_fkey"
    FOREIGN KEY ("roomId") REFERENCES "Room"("id")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "RoomImage_roomId_idx"
  ON "RoomImage"("roomId");